server:
  port: ${port:8080}
spring:
  resources:
    add-mappings: false
  mvc:
    throw-exception-if-no-handler-found: true
env:
  datasource:
    url: h2:mem:;MODE=PostgreSQL;INIT=RUNSCRIPT FROM './database/sql/01_ddl.sql'\;RUNSCRIPT FROM './database/sql/02_sampledata.sql'
    driverClassName: org.h2.Driver