on:
  release:
    types: [published]
name: Deploy Development (Frontend)
jobs:
  release:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Deploy Firebase Hosting
      run: |
        cd mosakin-frontend
        sh npminstall-rockjson-check.sh
        npm test
        npm run build:dev
        npm run deploy:dev
      env:
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}